/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rakitic.ljetnizadatak;


import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.ArrayList;


import java.util.List;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Borna
 */
public class RadSBazom extends javax.swing.JFrame {
    private Connection veza;
    private NamedParameterStatement izraz;
    

      
   
    /**
     * Creates new form RadSBazom
     */
    public RadSBazom() {
        initComponents();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        try {
             veza = DriverManager.getConnection("jdbc:mysql://localhost/1_hnl?" +
                                   "user=edunova&password=edunova&serverTimezone=CET&useUnicode=true&characterEncoding=utf-8");
            
             List<Klub> klub = ucitajIzBaze();
             KlubTableModel model = new KlubTableModel(klub);
             tblKlub.setModel(model);
            
        } catch (Exception ex) {
           ex.printStackTrace();
        }
        
        
                     
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKlub = new javax.swing.JTable();
        lblNK = new javax.swing.JLabel();
        lblIS = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        txtNK = new javax.swing.JTextField();
        txtIS = new javax.swing.JTextField();
        txtGrad = new javax.swing.JTextField();
        lblPoruka = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnUredi = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKlub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naziv Kluba", "Ime stadiona", "Grad"
            }
        ));
        tblKlub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKlubMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKlub);

        lblNK.setText("Naziv kluba:");

        lblIS.setText("Ime stadiona:");

        lblGrad.setText("Grad:");

        lblPoruka.setForeground(new java.awt.Color(255, 0, 0));

        btnDodaj.setText("Dodaj klub");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnUredi.setText("Uredi");
        btnUredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrediActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(190, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNK)
                                    .addComponent(txtIS)
                                    .addComponent(txtGrad, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(btnUredi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUredi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(596, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {
            String nazivKluba = txtNK.getText();
            String imeStadiona = txtIS.getText();
            String grad = txtGrad.getText();
            izraz = new NamedParameterStatement(veza, "insert into Klub(grad,ime_stadiona,naziv) value (:naziv_kluba,:ime_stadiona,:grad)");
            izraz.setString("naziv_kluba", nazivKluba);
            izraz.setString("ime_stadiona",imeStadiona);
            izraz.setString("grad", grad);
            izraz.execute();
            izraz.close();
             List<Klub> klub = ucitajIzBaze();
             KlubTableModel model = new KlubTableModel(klub);
             tblKlub.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
                 
        
        
        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnUrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrediActionPerformed
         try {
             int row = tblKlub.getSelectedRow();
             int sifra = (int) tblKlub.getValueAt(row,KlubTableModel.SIFRA_COL);
            String nazivKluba = txtNK.getText();
            String imeStadiona = txtIS.getText();
            String grad = txtGrad.getText();
            izraz = new NamedParameterStatement(veza, "update klub set naziv=:naziv_kluba, grad=:grad, ime_stadiona=:ime_stadiona where sifra=:sifra");
            izraz.setInt("sifra",sifra);
            izraz.setString("naziv_kluba", nazivKluba);
            izraz.setString("ime_stadiona",imeStadiona);
            izraz.setString("grad", grad);
            izraz.execute();
            izraz.close();
             List<Klub> klub = ucitajIzBaze();
             KlubTableModel model = new KlubTableModel(klub);
             tblKlub.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUrediActionPerformed

    private void tblKlubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKlubMouseClicked
        int row = tblKlub.getSelectedRow();
        Klub k = (Klub) tblKlub.getValueAt(row,KlubTableModel.OBJECT_COL);
        
        txtNK.setText(k.getNazivKluba());
        txtIS.setText(k.getImeStadiona());
        txtGrad.setText(k.getGrad());
    }//GEN-LAST:event_tblKlubMouseClicked

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {int row = tblKlub.getSelectedRow();
        int sifra = (int) tblKlub.getValueAt(row,KlubTableModel.SIFRA_COL);
        izraz = new NamedParameterStatement(veza, "delete from klub where sifra=:sifra");
            izraz.setInt("sifra",sifra);
            izraz.execute();
            izraz.close();
             List<Klub> klub = ucitajIzBaze();
             KlubTableModel model = new KlubTableModel(klub);
             tblKlub.setModel(model);
            
        } catch (Exception e) {
        }

        
    }//GEN-LAST:event_btnObrisiActionPerformed

   
   
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadSBazom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadSBazom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadSBazom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadSBazom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RadSBazom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnUredi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblIS;
    private javax.swing.JLabel lblNK;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JTable tblKlub;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtIS;
    private javax.swing.JTextField txtNK;
    // End of variables declaration//GEN-END:variables

    
   public List<Klub> ucitajIzBaze() throws Exception{
       List<Klub> klub = new ArrayList<>();
       Statement stmt = null;
       ResultSet rs = null;
       try {
           stmt=veza.createStatement();
           rs=stmt.executeQuery("select * from klub");
           while(rs.next()){
               Klub k = convertRowsToKlub(rs);
               klub.add(k);
           }
           return klub;
       } 
           
       finally{
           rs.close();
           stmt.close();
       }
        
       
       
               
     
   }
   
   public Klub convertRowsToKlub(ResultSet rs) throws SQLException{
       int sifra = rs.getInt("sifra");
       String nazivKluba = rs.getString("naziv");
       String imeStadiona = rs.getString("ime_stadiona");
       String grad = rs.getString("grad");
       Klub k = new Klub(sifra, nazivKluba, imeStadiona, grad);
       return k;
       
       
   }
    

}










